# Generated by Django 3.1.1 on 2020-11-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='custom_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='custom_user.user')),
                ('recruiting_manager', models.CharField(default='No Recruiting MGR Entered', max_length=40)),
                ('company', models.CharField(default='No Company Entered', max_length=40)),
                ('city', models.CharField(choices=[('BIRMINGHAM', 'Birmingham'), ('BRADFORD', 'Bradford'), ('BRISTOL', 'Bristol'), ('LEEDS', 'Leeds'), ('LIVERPOOL', 'Liverpool'), ('LONDON', 'London'), ('MANCHESTER', 'Manchester'), ('NEWCASTLE', 'Newcastle'), ('SHEFFIELD', 'Sheffield'), ('SOUTHAMPTON', 'Southampton')], default='LONDON', max_length=11)),
            ],
        ),
    ]
