# Generated by Django 3.1.1 on 2020-11-26 11:19

from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(default='CV to be added', upload_to=recruit.models.user_directory_path),
        ),
    ]
