# Generated by Django 3.1.1 on 2020-11-26 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_candidate_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV', models.FileField(upload_to=recruit.models.user_directory_path)),
                ('is_succesful', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20, 0), django.core.validators.MaxValueValidator(100, 0)])),
                ('city', models.CharField(choices=[('BIRMINGHAM', 'Birmingham'), ('BRADFORD', 'Bradford'), ('BRISTOL', 'Bristol'), ('LEEDS', 'Leeds'), ('LIVERPOOL', 'Liverpool'), ('LONDON', 'London'), ('MANCHESTER', 'Manchester'), ('NEWCASTLE', 'Newcastle'), ('SHEFFIELD', 'Sheffield'), ('SOUTHAMPTON', 'Southampton')], default='LONDON', max_length=11)),
                ('category', models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('CONSULTING', 'Consulting'), ('ENGINEERING', 'Engineering'), ('FINANCE', 'Finance'), ('RETAIL', 'Retail'), ('SALES', 'Sales')], default='ADMINISTRATION', max_length=15)),
                ('max_applications', models.PositiveSmallIntegerField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('applications', models.ManyToManyField(related_name='submissions', to='recruit.Application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.employer')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.vacancy'),
        ),
    ]
