# Generated by Django 3.1.1 on 2020-11-26 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20201126_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(default='Job Title', max_length=35),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='main_duties',
            field=models.TextField(default='Main Duties', validators=[django.core.validators.MinLengthValidator(150), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='person_spec',
            field=models.TextField(default='Person Spec', validators=[django.core.validators.MinLengthValidator(150), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=20000, validators=[django.core.validators.MinValueValidator(20, 0), django.core.validators.MaxValueValidator(100, 0)]),
        ),
    ]
