# Generated by Django 3.1.1 on 2020-11-26 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20201126_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('CONSULTING', 'Consulting'), ('ENGINEERING', 'Engineering'), ('FINANCE', 'Finance'), ('RETAIL', 'Retail'), ('SALES', 'Sales')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(choices=[('BIRMINGHAM', 'Birmingham'), ('BRADFORD', 'Bradford'), ('BRISTOL', 'Bristol'), ('LEEDS', 'Leeds'), ('LIVERPOOL', 'Liverpool'), ('LONDON', 'London'), ('MANCHESTER', 'Manchester'), ('NEWCASTLE', 'Newcastle'), ('SHEFFIELD', 'Sheffield'), ('SOUTHAMPTON', 'Southampton')], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='main_duties',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(150), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='person_spec',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(150), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
