# Generated by Django 3.1.1 on 2020-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20201127_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'vacancies'},
        ),
    ]
