# Generated by Django 3.1.1 on 2020-11-27 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20201127_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='main_duties',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(650), django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='person_spec',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(650), django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
