# Generated by Django 3.1.1 on 2020-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20201127_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_applications',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
