# Generated by Django 3.1.1 on 2020-11-27 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_auto_20201127_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(99000)]),
        ),
    ]
