# Generated by Django 3.1.1 on 2020-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_auto_20201127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
