# Generated by Django 3.1.1 on 2020-11-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0013_auto_20201128_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
