# Generated by Django 3.1.1 on 2020-12-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0015_auto_20201129_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='CV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.candidate'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
