# Generated by Django 3.1.1 on 2020-12-04 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_auto_20201204_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
