# Generated by Django 3.1.1 on 2020-12-10 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0020_auto_20201210_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
