# Generated by Django 3.1.1 on 2020-12-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_application_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
