# Generated by Django 3.1.1 on 2020-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0022_auto_20201210_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
