# Generated by Django 3.1.1 on 2020-12-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_auto_20201211_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_succesful',
        ),
        migrations.AddField(
            model_name='application',
            name='stages',
            field=models.CharField(choices=[('pre-selection', 'PRE-SELECTION'), ('shortlisted', 'SHORTLISTED'), ('rejected pre-interview', 'REJECTED PRE-INTERVIEW'), ('rejected post-interview', 'REJECTED POST-INTERVIEW'), ('successful', 'SUCCESSFUL')], default='pre-selection', max_length=25),
        ),
    ]
