# Generated by Django 3.1.1 on 2020-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0025_auto_20201211_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='applications',
            field=models.ManyToManyField(blank=True, to='recruit.Application'),
        ),
    ]
