# Generated by Django 3.1.1 on 2020-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0026_auto_20201212_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
