# Generated by Django 3.1.1 on 2020-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0027_auto_20201212_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=None),
        ),
    ]
