# Generated by Django 3.1.1 on 2020-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0028_auto_20201212_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='recruit.Application'),
        ),
    ]
