# Generated by Django 3.1.1 on 2020-12-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0030_auto_20201217_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='active',
        ),
    ]
