# Generated by Django 3.1.1 on 2020-12-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0031_remove_vacancy_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='applications',
        ),
    ]
