# Generated by Django 3.1.1 on 2020-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0035_auto_20201226_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, ''), (2, 'Applications shortlisted'), (3, 'Interviewing')], default=1),
        ),
    ]
