# Generated by Django 3.1.1 on 2020-12-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0037_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateField(default=None, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InterviewSlots',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruit.application')),
                ('time', models.TimeField(default=None)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.interview', to_field='date')),
            ],
        ),
    ]
