# Generated by Django 3.1.1 on 2020-12-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0038_auto_20201228_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewslots',
            options={'verbose_name_plural': 'interview slots'},
        ),
        migrations.RemoveField(
            model_name='interviewslots',
            name='date',
        ),
    ]
