# Generated by Django 3.1.1 on 2020-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0039_auto_20201228_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
