# Generated by Django 3.1.1 on 2020-12-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0040_auto_20201228_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
