# Generated by Django 3.1.1 on 2020-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0042_auto_20201229_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewslot',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='start_time',
        ),
        migrations.AddField(
            model_name='interview',
            name='starting_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
