# Generated by Django 3.1.1 on 2020-12-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0043_auto_20201229_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='time_interval',
            field=models.SmallIntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '1 hr'), (75, '1 hr 15 min'), (90, '1 hr 30 min')], default=30),
        ),
    ]
