# Generated by Django 3.1.1 on 2020-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0044_interview_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewslot',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
