# Generated by Django 3.1.1 on 2021-01-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0045_auto_20201229_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='succesful_candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.application'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, ''), (2, 'Applications shortlisted'), (3, 'Interviewing'), (4, 'Pending succesful candidate selection')], default=1),
        ),
    ]
