# Generated by Django 3.1.1 on 2021-01-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0046_auto_20210104_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='succesful_candidate',
            new_name='successful_candidate',
        ),
    ]
