# Generated by Django 3.1.1 on 2021-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0047_auto_20210104_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, ''), (2, 'Applications shortlisted'), (3, 'Interviewing'), (4, 'Pending succesful candidate selection'), (5, 'Vacancy filled')], default=1),
        ),
    ]
