# Generated by Django 3.1.1 on 2021-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0048_auto_20210104_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='stage',
            field=models.SmallIntegerField(choices=[(0, 'Obsolete'), (1, ''), (2, 'Applications shortlisted'), (3, 'Interviewing'), (4, 'Post-Interview'), (5, 'Vacancy filled')], default=1),
        ),
    ]
